alias load_python2="module load python py_packages vcflib tabix"
alias load_python3="module load python/3.6.2 py_packages/3.6"
alias moudule_grep="module avail 2>&1 | grep"
#load_modules
export GRCH37=/hpc/genome_fa/GRCh37.p13.genome.fa


# necessary for installing anaconda3
#export PYTHONPATH=
#/hpc/packages/minerva-common/py_packages/2.7/lib/python2.7/site-packages:/hpc/packages/minerva-common/python/2.7.14/lib/python2.7/site-packages

# added by Anaconda3 installer
export PATH="$HOME/local/anaconda3/bin:$PATH"
